server:
  port: 5555
spring:
  application:
    name: router
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    comsumer-service:
      path: /comsumer/**
      serviceId: comsumer-service
    producer-service:
      path: /producer/**
      serviceId: producer-service